version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend_docker
    ports:
      - 8080:8080
    networks:
      - app-network
  frontend:
    build:
      context: .
      dockerfile: frontend_docker
    ports:
      - 3000:3000
    networks:
      - app-network
networks:
  app-network: