version: '3.9'
services:
  postgresdb:
    image: postgres
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=Admin
     - POSTGRES_PASSWORD=3v4AVNwH87q6CKVuuiUq
    volumes:
     - db-data:/var/lib/postgresql/data

volumes:
 db-data:     

      